In [40]:
import torch
import numpy as np

## 1.torch

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [3]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [5]:
#NumPy array to Tenso
n = np.ones(5)
t = torch.from_numpy(n)
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


In [6]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3864, 0.9858],
        [0.2574, 0.0559]]) 



In [7]:
tensor = torch.rand(3, 4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [9]:
x= torch.arange(5)
print(x)
y= torch.arange(1, 4)
print(y)
z= torch.arange(1, 2.5, 0.5)
print(z)

tensor([0, 1, 2, 3, 4])
tensor([1, 2, 3])
tensor([1.0000, 1.5000, 2.0000])


In [10]:
torch.linspace(-10, 10, steps=5)

tensor([-10.,  -5.,   0.,   5.,  10.])

In [11]:
 torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [12]:
x = torch.arange(4, dtype=torch.float)
A = torch.complex(x, x).reshape(2, 2)
A

tensor([[0.+0.j, 1.+1.j],
        [2.+2.j, 3.+3.j]])

In [13]:
A.adjoint()

tensor([[0.-0.j, 2.-2.j],
        [1.-1.j, 3.-3.j]])

In [14]:
t = torch.tensor([1, 0, 1])
torch.argwhere(t)

tensor([[0],
        [2]])

In [15]:
t = torch.tensor([[1, 0, 1], [0, 1, 1]])
torch.argwhere(t)

tensor([[0, 0],
        [0, 2],
        [1, 1],
        [1, 2]])

In [16]:
a = torch.arange(10).reshape(5,2)
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [17]:
torch.split(a, 2)

(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7]]),
 tensor([[8, 9]]))

In [23]:
torch.split(a, [2,3])

(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7],
         [8, 9]]))

In [28]:
x = torch.ones(2, 2, 2)
x

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [30]:
y = torch.squeeze(x, 0)
y

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [31]:
y = torch.squeeze(x, 1)
y

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [32]:
#TORCH.STACK 沿着一个新的维度连接张量序列。

In [37]:
a = torch.rand(1, 2)
a.size()

torch.Size([1, 2])

In [38]:
a = torch.randn(4, 4) #标准正态分布
a

tensor([[ 2.2304,  0.5900,  0.5076, -0.8966],
        [ 0.9255, -2.3464, -0.5028, -0.2398],
        [-0.9496, -1.3896, -1.1352, -0.1793],
        [ 0.7590, -1.5065,  0.8192, -1.1993]])

In [41]:
torch.max(a, 1) #返回值和索引  行不变列之间比较

torch.return_types.max(
values=tensor([ 2.2304,  0.9255, -0.1793,  0.8192]),
indices=tensor([0, 0, 3, 2]))

In [44]:
x = torch.randn(3, 4)
x

tensor([[ 0.5616,  1.2104,  1.3590, -1.5414],
        [ 0.3703,  0.1656, -0.0166, -0.8261],
        [ 0.4228, -0.6977,  0.6207, -0.0637]])

In [45]:
sorted, indices = torch.sort(x)
sorted

tensor([[-1.5414,  0.5616,  1.2104,  1.3590],
        [-0.8261, -0.0166,  0.1656,  0.3703],
        [-0.6977, -0.0637,  0.4228,  0.6207]])

## 2.torch.nn