In [2]:
import torch
torch.__version__

'1.8.1'

In [4]:
x = torch.empty(5, 3)
x

tensor([[8.9082e-39, 1.0194e-38, 9.1837e-39],
        [4.6837e-39, 9.9184e-39, 9.0000e-39],
        [1.0561e-38, 1.0653e-38, 4.1327e-39],
        [8.9082e-39, 9.8265e-39, 9.4592e-39],
        [1.0561e-38, 1.0653e-38, 1.0469e-38]])

In [5]:
x = torch.rand(5, 3)
x

tensor([[0.5627, 0.7216, 0.0968],
        [0.0203, 0.9491, 0.6229],
        [0.4473, 0.4576, 0.3112],
        [0.4834, 0.7241, 0.5892],
        [0.6921, 0.1166, 0.1334]])

In [14]:
x= torch.zeros(5, 3, dtype=torch.long)
x


tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [13]:
x = torch.ones(5, 3, dtype=torch.long)
x

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [20]:
x = torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [21]:
x = x.new_ones(5, 3, dtype=torch.float)
x = torch.randn_like(x, dtype=torch.float)
x

tensor([[ 1.4889, -1.9421, -1.6846],
        [ 1.5213, -1.1072, -0.4727],
        [ 0.0681, -1.1464,  0.4548],
        [-0.7054, -0.5500,  0.2406],
        [ 0.7257, -0.0020,  0.4138]])

In [22]:
x.size()

torch.Size([5, 3])

In [23]:
y = torch.rand(5, 3)
x + y

tensor([[ 1.8153, -1.1875, -1.0335],
        [ 2.0318, -0.6211,  0.3514],
        [ 0.1709, -0.9926,  1.3782],
        [-0.5079, -0.2946,  0.9303],
        [ 1.3451,  0.6857,  0.8366]])

In [24]:
torch.add(x, y)

tensor([[ 1.8153, -1.1875, -1.0335],
        [ 2.0318, -0.6211,  0.3514],
        [ 0.1709, -0.9926,  1.3782],
        [-0.5079, -0.2946,  0.9303],
        [ 1.3451,  0.6857,  0.8366]])

In [25]:
x[:, 1]

tensor([-1.9421, -1.1072, -1.1464, -0.5500, -0.0020])

### view操作改变矩阵维度

In [29]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x)
print(x.size(), y.size(), z.size())

tensor([[ 0.2981,  0.8467,  0.5758,  0.3258],
        [-0.0699, -1.2297, -2.9517, -2.9644],
        [-0.1604, -1.5747,  0.5357, -0.2505],
        [ 1.7181, -0.6698, -0.9672, -0.8050]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### 与numpy的协同操作

In [30]:
a = torch.ones(5)
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [31]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)