np.random模块常用函数

In [1]:
import numpy as np


In [2]:
x = np.random.random([3, 4])
x

array([[0.56519544, 0.67799245, 0.5310832 , 0.85221463],
       [0.36773352, 0.37206146, 0.85653865, 0.86467806],
       [0.79135496, 0.82125128, 0.07284303, 0.06162717]])

In [3]:
y = np.random.uniform()
y

0.2798743301273554

In [4]:
y = np.random.uniform([3, 4])
y

array([1.26309809, 2.1683893 ])

In [5]:
z = np.random.randint(4)
z

3

In [10]:
np.random.seed(123)
nd4 = np.random.randn(2, 3)
print(nd4)
np.random.shuffle(nd4)
print("随机打乱后的数据:")
print(nd4)
print(type(nd4))

[[-1.0856306   0.99734545  0.2829785 ]
 [-1.50629471 -0.57860025  1.65143654]]
随机打乱后的数据:
[[-1.50629471 -0.57860025  1.65143654]
 [-1.0856306   0.99734545  0.2829785 ]]
<class 'numpy.ndarray'>


In [12]:
nd1 = np.zeros((3, 4))
nd1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
nd3 = np.ones((3, 4))
nd3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
nd2 = np.empty((2, 2))
nd2

array([[0.79135496, 0.82125128],
       [0.07284303, 0.06162717]])

In [17]:
nd4 = np.zeros_like(nd1)
nd4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
nd5 = np.eye(5)
nd5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
nd6 = np.full((3,4), 666)
nd6

array([[666, 666, 666, 666],
       [666, 666, 666, 666],
       [666, 666, 666, 666]])

In [21]:
nd7 = np.diag([1, 2, 3])
nd7

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [27]:
nd8 = np.arange(5)
nd8

array([0, 1, 2, 3, 4])

In [28]:
nd9 = np.linspace(1, 10, 10)
nd9

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [32]:
nd1 = np.random.random([10])
print(nd1)
nd1[3]

[0.37380143 0.23451288 0.98799529 0.76599595 0.77700444 0.02798196
 0.17390652 0.15408224 0.07708648 0.8898657 ]


0.7659959501929948

In [33]:
nd1[1:3]

array([0.23451288, 0.98799529])

In [34]:
nd1[::-1]

array([0.8898657 , 0.07708648, 0.15408224, 0.17390652, 0.02798196,
       0.77700444, 0.76599595, 0.98799529, 0.23451288, 0.37380143])

In [36]:
nd2 = np.arange(25).reshape([5, 5])
print(nd2)
nd2[1:3, 1:3]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 6,  7],
       [11, 12]])

In [37]:
nd2[(nd2>3) & (nd2<10)]

array([4, 5, 6, 7, 8, 9])

In [38]:
nd2[[1,2]]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [39]:
nd2[:,1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17],
       [21, 22]])

In [45]:
a = np.arange(1, 25)
print(a)
c1 = np.random.choice(a, size=(3,3))
print(c1)
c2 = np.random.choice(a,size=(3,3), replace=False)
c2

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 7 18 15]
 [11  4 21]
 [ 4  2 16]]


array([[ 8, 18,  3],
       [13, 11, 23],
       [22,  7,  5]])

算术运算

In [48]:
x1 = np.arange(12).reshape(3,4)
x1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
x2 = np.arange(2,14).reshape(3,4)
x2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [51]:
x = np.multiply(x1, x2)
x

array([[  0,   3,   8,  15],
       [ 24,  35,  48,  63],
       [ 80,  99, 120, 143]])

In [52]:
x = x1*x2
x

array([[  0,   3,   8,  15],
       [ 24,  35,  48,  63],
       [ 80,  99, 120, 143]])

In [53]:
x1 = np.array([[1,2],[3,4]])
print(x1)
x2 = np.array([[1,2,3],[4, 5, 6]])
print(x2)
x = np.dot(x1, x2)
x

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]]


array([[ 9, 12, 15],
       [19, 26, 33]])

In [55]:
a = np.arange(12)
b = a.reshape(3, 4)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [59]:
#resize修改向量本身
a = np.arange(12)
b = a.resize(3, 4)
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
None


In [60]:
a = np.arange(15).reshape(5,-1)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [62]:
#按列展平
b = a.ravel("F")
b

array([ 0,  3,  6,  9, 12,  1,  4,  7, 10, 13,  2,  5,  8, 11, 14])

In [63]:
c = a.ravel()
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [64]:
d = np.floor(c[3])
d

3.0

In [66]:
arr = np.arange(24).reshape(2,3,4)
print(arr.shape)
print(arr.transpose(1,2,0).shape)

(2, 3, 4)
(3, 4, 2)


In [72]:
a = np.arange(4).reshape(2, 2)
b = np.arange(4).reshape(2, 2)
#按行合并
c = np.append(a, b, axis=0)
print("按行合并后的结果")
print(c)
print("合并后的数据维度",c.shape)
#按列合并
d = np.append(a, b, axis=1)
print("按列合并后的结果")
print(d)
print("合并后的数据维度",d.shape)

按行合并后的结果
[[0 1]
 [2 3]
 [0 1]
 [2 3]]
合并后的数据维度 (4, 2)
按列合并后的结果
[[0 1 0 1]
 [2 3 2 3]]
合并后的数据维度 (2, 4)


In [74]:
a = np.arange(16).reshape(4, 4)
b = np.arange(16).reshape(4, 4)
#按行合并
c = np.append(a, b, axis=0)
print("按行合并后的结果")
print(c)
print("合并后的数据维度",c.shape)
#按列合并
d = np.append(a, b, axis=1)
print("按列合并后的结果")
print(d)
print("合并后的数据维度",d.shape)

按行合并后的结果
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
合并后的数据维度 (8, 4)
按列合并后的结果
[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]
 [12 13 14 15 12 13 14 15]]
合并后的数据维度 (4, 8)


In [78]:
a = np.array([[1, 2],[3, 4]])
b = np.array([[5, 6],[7, 8]])
c = np.stack((a,b), axis=0)
print(c.shape)

(2, 2, 2)


In [79]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9
